// Generated by scripts/registry.js (`bun run registry`); do not edit.
import maps_flagfall from './flagfall/index.js'
import { lobby } from './lobby.js'
import { mapRegistry } from './recipes.js'
import { overthrow } from './overthrow.js'

export const DEFAULT_MAP = 'overthrow'
export const maps = {
	flagfall: maps_flagfall,
	lobby,
	overthrow,
}
export const { playableMaps, onlineMaps, mapLayout, matchRecipe } = mapRegistry(maps, DEFAULT_MAP)
