// Generated by scripts/registry.js (`bun run registry`); do not edit.
import maps_flagfall from './flagfall/index.js'
import maps_lobby from './lobby/index.js'
import maps_overthrow from './overthrow/index.js'
import { mapRegistry } from './recipes.js'

export const DEFAULT_MAP = 'overthrow'
export const maps = {
	flagfall: maps_flagfall,
	lobby: maps_lobby,
	overthrow: maps_overthrow,
}
export const { playableMaps, onlineMaps, mapLayout, matchRecipe } = mapRegistry(maps, DEFAULT_MAP)
