// Generated by scripts/registry.js (`bun run registry`); do not edit.
import * as flagfall_ground from './flagfall/ground.js'
import * as flagfall_scenery from './flagfall/scenery.js'

export default {
	flagfall: { ...flagfall_ground, ...flagfall_scenery },
}
