// Generated by scripts/registry.js (`bun run registry`); do not edit.
import * as flagfall_ground from './flagfall/ground.js'
import * as flagfall_scenery from './flagfall/scenery.js'
import * as lobby_ground from './lobby/ground.js'
import * as overthrow_ground from './overthrow/ground.js'
import * as overthrow_scenery from './overthrow/scenery.js'

export default {
	flagfall: { ...flagfall_ground, ...flagfall_scenery },
	lobby: { ...lobby_ground },
	overthrow: { ...overthrow_ground, ...overthrow_scenery },
}
