// Generated by scripts/registry.js (`bun run registry`); do not edit.
import heroes_carom from './carom/index.js'
import heroes_fletcher from './fletcher/index.js'
import heroes_mitts from './mitts/index.js'

export default {
	carom: heroes_carom,
	fletcher: heroes_fletcher,
	mitts: heroes_mitts,
}
