// Generated by scripts/registry.js (`bun run registry`); do not edit.
import * as carom_costume from './carom/costume.js'
import * as fletcher_costume from './fletcher/costume.js'
import * as fletcher_numbers from './fletcher/numbers.js'

export default {
	carom: { costume: carom_costume },
	fletcher: { costume: fletcher_costume, numbers: fletcher_numbers },
}
