// --- Tunables ----------------------------------------------------------------
// Moba's live values (docs/moba-plan.md, "Feel numbers"), shared by the debug GUI, the sim and DOM-free tests. Metres and seconds.
export const tune = {
	testing: {
		speed: 1,
		speedMin: 0.25,
		speedMax: 16,
		speedStep: 0.25,
		seedMax: 0xffffffff,
		rosterMax: 24,
	},
	onboarding: {
		objectiveLife: 7,
		youLife: 8,
		timerLife: 12,
		xpLife: 9,
		ballHintLife: 10,
		goalLift: { tower: 4.5, core: 7.5 },
		walkDistance: 10,
		arrowFade: 0.8,
		crowdRadius: 4,
		crowdCount: 2,
		ringRadius: 0.85,
		ringWidth: 0.18,
		ringY: 0.18,
		ringBorderY: 0.165,
		segments: 64,
		arrowY: 0.2,
		arrowOffset: 1.5,
		arrowLength: 2.5,
		arrowWidth: 0.7,
		arrowHead: 0.8,
		stipplePixels: 2,
		labelHeight: 1.3,
		levelLife: 2.2,
		levelRise: 1.2,
		levelPulse: 0.55,
		pointerMargin: 64,
		pointerTop: 115,
		pointerBottom: 180,
		stickerBorder: 3,
		stickerShadow: 4,
		stickerCorner: 12,
		stickerPadding: 8,
		font: 16,
		objectiveFont: 26,
		objectiveTop: 118,
		hintBottom: 160,
		hintWidth: 520,
		timerFont: 10,
	},
	// Static layout and dressing: applies on mode restart.
	map: {
		name: 'Overthrow',
		halfX: 52,
		halfZ: 13,
		thickness: 1,
		baseWallX: 28,
		throat: 8,
		spawnX: 48,
		spawnSpacing: 1.5,
		hedgeInnerX: 12,
		hedgeOuterX: 24,
		hedgeInnerZ: 6,
		hedgeOuterZ: 8,
		hedgeHeight: 1.2,
		scallopRadius: 0.5,
		scallopSpacing: 0.8,
		plazaRadius: 9,
		pillarX: 4.5,
		pillarZ: 4,
		guardX: 13,
		guardZ: 3,
		pillarRadius: 0.7,
		pillarHeight: 1.8,
		pillarSegments: 24,
		capScale: 0.8,
		capHeight: 0.04,
		printLayers: { road: 0.015, dots: 0.03, lobby: 0.045, marks: 0.06, seams: 0.075 },
		// Ground markers (pings, hover, aim line) must sit above every print layer
		markerLayers: { aim: 0.09, aimTip: 0.092, hover: 0.095, ping: 0.1 },
		lineWidth: 0.06,
		dashLength: 1,
		dashSpacing: 2,
		dotSpacing: 1,
		dotRadius: 0.045,
		printSegments: 32,
		wallHeight: 2.4,
		boundaryThickness: 0.5,
		dummyPosts: [
			{ x: -3, z: -7 },
			{ x: 5, z: -10 },
		],
	},
	// Shared match presentation, first built for Overthrow; applies on map restart.
	overthrowTerrain: {
		margin: 1.6,
		jag: 0.8,
		step: 3,
		seed: 73,
		rockDepth: 5,
		rockFlare: 1.4,
		rockBands: 3,
		groundY: 0.005,
		chalkY: 0.01,
		patchScale: 3,
		patchContrast: 0.025,
		chalkWidth: 0.11,
		courtInset: 1.4,
		chalkSegments: 96,
		surroundSize: 600,
		surroundDrop: 12,
		mesaSpacing: 22,
		mesaRows: 3,
		mesaRadius: 7,
		mesaHeight: 5,
		mesaVariation: 0.2,
		mesaTaper: 1.3,
		mesaSegments: 7,
		colors: {
			tarmac: '#e4dfcf',
			chalk: '#f5f1e5',
			rock: '#aaa49b',
			rockDark: '#656575',
			surround: '#555669',
			mesa: '#536c6b',
		},
		palette: { page: 0x555669, courtShade: 0x708883, scenery: 0x899b9b },
	},
	// Flagfall: two lanes on the shared court in the shallows. All geometry applies on restart.
	flagfall: {
		name: 'Flagfall',
		scale: 0.9, // one multiplier for every layout metre; applies on restart
		palette: { page: 0x536e79 },
		rockDepth: 1.8,
		// Flagfall scenery only; metres before map scale, all apply on restart.
		finish: {
			anisotropy: 8,
			courtAsset: '/scenery/flagfall-court.webp',
			courtMetres: 8,
			courtTexture: 3, // grit contrast gain; 1 is the tile as painted
			courtRange: 0.07, // grit never moves the floor more than ±7%
			courtMean: 0.731, // linear luminance mean; modulate without lowering the pale floor
			hedgeAsset: '/scenery/flagfall-hedge.webp',
			hedgeMetres: 5,
			hedgeTexture: 0.35,
			warm: '#f2e5c9',
			cool: '#c7cdd0',
			lightStrength: 0.2,
			lightSpread: 0.85,
			contactPixelsPerMetre: 12,
			contactWidth: 1.2,
			contactStrength: 0.3,
			edgeWidth: 1.3,
			edgeStrength: 0.1,
			rock: '#b3a28c',
			rockDark: '#617175',
			rockGrain: 0.045,
			rockGrainMetres: 0.04,
			rockStrata: 0.22,
			wetHeight: 0.5,
			wetStrength: 0.28,
			cover: '#70877a',
			wall: '#a69680', // base blocks are sandstone walls, not hedges
			wallBlock: [1.5, 0.5], // block length, course height
			wallFlag: 3, // square paving on the wall tops
			pillar: '#b0a690',
			pillarCourse: 0.6, // stacked drums
			pillarFlutes: 14,
			fluteDepth: 0.07,
			mortar: 0.14, // joint darkening, never ink
			mortarWidth: 0.04,
			mottle: 0.07, // tone drift between blocks
			footHeight: 0.4,
			footShade: 0.16,
			coverShade: 0.23,
		},
		water: {
			asset: '/scenery/flagfall-water.webp', // generated shallows; flat fallback if unavailable
			width: 165, // image width in metres; height follows its native aspect
			fallbackSize: 600,
			drop: 1.7,
			layerGap: 0.015,
			color: '#536e79',
			foamColor: '#b3c8c2',
			padColor: '#618b7e',
			detailAsset: '/scenery/flagfall-ripple.webp',
			detailMetres: 7,
			detailStrength: 3, // caustic contrast gain; 1 is the tile as painted
			detailMean: 0.461, // grey tile's linear luminance mean, so ripples don't turn the plate muddy
			detailSpeed: 0.035,
			hazeDistance: 28,
			hazeStrength: 0.32,
			shoreWidth: 0.5,
			shoreOpacity: 0.75,
			shoreBreak: 1, // 0 a soft glow, 1 a crisp broken foam line
			reflectionWidth: 2.2,
			reflectionOpacity: 0.14,
			padNotch: 0.16,
			padRim: 0.025,
			padRimColor: '#90ab92',
			padVeinColor: '#7da18d',
			padVeinWidth: 0.018,
			padVeinReach: 0.75,
			padVeinAngles: [-0.8, 0, 0.8],
			padAspect: 0.82,
			flowerEvery: 3,
			flowerRadius: 0.12,
			flowerColor: '#d3c4ce',
			flowerPetals: 5,
			reedCount: 12,
			reedBlades: 7,
			reedHeight: 0.9,
			reedWidth: 0.06,
			reedSpread: 0.35,
			reedOffset: 6,
			reedColor: '#607c72',
			lightCount: 8,
			lightRadius: 0.08,
			lightHalo: 0.35,
			lightHeight: 0.7,
			lightColor: '#c2d5c2',
			lightOpacity: 0.55,
			lightTravel: 0.6,
			lightTime: 18,
			cloudColor: '#b9b8c9',
			feather: 0.1, // soften the finite plate into the flat sea; UV fraction
			shimmer: 0.045,
			rippleLength: 2.8,
			rippleTime: 9,
			foamCount: 24,
			foamLength: 6,
			foamWidth: 0.12,
			foamOffset: 2.5,
			foamTravel: 2,
			foamTime: 12,
			foamOpacity: 0.24,
			ringCount: 16,
			ringRadius: 0.8,
			ringWidth: 0.04,
			ringGrow: 0.8,
			ringTime: 7,
			ringOpacity: 0.18,
			padCount: 12,
			padRadius: 0.65,
			padOffset: 1.5,
			padSpread: 3,
			padBob: 0.035,
			padTime: 6,
			clouds: true, // first effect to drop if the frame budget is threatened
			cloudCount: 4,
			cloudLength: 15,
			cloudWidth: 5,
			cloudOffset: 9,
			cloudTravel: 4,
			cloudTime: 45,
			cloudOpacity: 0.09,
			segments: 32,
		},
		// Broken fence runs on the safe rim, not colliders or a new fence style.
		fence: {
			runs: [
				{ from: [-0.96, -1], to: [-0.7, -1] },
				{ from: [-0.28, -1], to: [0.28, -1] },
				{ from: [0.7, -1], to: [0.96, -1] },
				{ from: [-1, -0.28], to: [-1, 0.28] },
				{ from: [1, -0.28], to: [1, 0.28] },
			],
			bollards: [
				[-0.5, -1],
				[0.5, -1],
				[-0.5, 1],
				[0.5, 1],
			],
		},
		bounds: { halfX: 52, halfZ: 20 },
		lane: { innerZ: 10, outerZ: 20, centreZ: 15 },
		yard: { halfX: 28, halfZ: 8 },
		baseBlock: { innerX: 28, outerX: 38, halfZ: 10 },
		baseX: 46,
		hedge: {
			innerZ: 8,
			outerZ: 10,
			runs: [
				[4, 12],
				[18, 28],
			],
		},
		pillarRadius: 1.1,
		yardPillars: { x: 7, z: 2 },
		towerPillars: { x: 13, z: 13 },
		spawns: { A: { x: -49, z: 0 }, B: { x: 49, z: 0 } },
		structures: { towerX: 18, fortX: 32, coreX: 42 },
		waveSpawnX: 40,
		posts: [
			{ x: -16, z: 3 },
			{ x: 16, z: -3 },
		],
		dummyPosts: [
			{ x: -2, z: -4 },
			{ x: 2, z: -4 },
		],
		print: {
			layers: { marks: 0.06, chalk: 0.075 },
			kerbWidth: 0.08,
			footprintWidth: 0.12,
			radii: { tower: 1.4, fort: 2, core: 2.6, post: 0.6 },
			poleRadius: 0.08,
			poleHeight: 6,
		},
	},
	// Lobby sim options apply on creation; map/match/training defaults do not read these.
	lobby: {
		capacity: 6,
		handoffFor: 3, // seconds of live lane simulation carrying the loading roster
		style: { line: 0.65, pastel: 0.65 },
		practice: { damage: 0, tell: 0.8, tellY: 0.23 },
		hud: { margin: 16 },
		inspect: {
			range: 16,
			scrollSpeed: 480,
			deadzone: 0.2,
			openSound: { freq: 710, slideTo: 1060, dur: 0.12, gain: 0.045, type: 'sine' },
			closeSound: { freq: 590, slideTo: 390, dur: 0.1, gain: 0.045, type: 'triangle' },
		},
		// Full playable lobby, live; height/back retain the lane's 58° pitch.
		camera: {
			x: 0,
			z: 2.65,
			height: 11,
			back: 6.875,
			fov: 66,
			fitAspect: 0.9,
			minAspect: 0.4,
			fitPasses: 6,
			fitGrowth: 1.2,
		},
		// Cardboard cutouts of the ready-line bots; geometry applies on lobby restart.
		cutout: {
			width: 1.8,
			height: 2.2,
			thickness: 0.08,
			printGap: 0.01,
			barWidth: 1.3,
			barHeight: 0.5,
			headRadius: 0.3,
			legHeight: 0.35,
			legWidth: 0.13,
			legSpread: 0.3,
			footWidth: 0.4,
			footHeight: 0.08,
			footDepth: 0.65,
			segments: 24,
		},
		// Picking from the hero row: the new body comes round edge-on, like a cutout turned on a pin.
		pick: {
			// Authored points that pick intents name heroes by; nothing stands there.
			x: 5.2,
			z: 0,
			spacing: 2,
			radius: 0.7,
			nameHeight: 1.9,
			flipTime: 0.25,
			flipEdge: 0.06,
			flipOvershoot: 0.12,
			sound: { freq: 620, slideTo: 980, dur: 0.14, gain: 0.08, type: 'triangle' },
			denySound: { freq: 120, slideTo: 70, dur: 0.18, gain: 0.1, type: 'square' },
		},
		ready: {
			// Authored ground prints and cardboard apply on restart; fill/activation timing is live.
			x: 2.65,
			z: 0,
			spacing: 1.7,
			width: 1.5,
			depth: 1.3,
			fillTime: 1,
			borderWidth: 0.045,
			boxY: 0.19,
			borderY: 0.185,
			fillY: 0.195,
			cardScale: 0.36,
			// A bot's hero floats over its seat as a hologram.
			hologram: {
				float: 0.22,
				bob: 0.06,
				bobRate: 1.8,
				sway: 0.5,
				swayRate: 0.5,
				opacity: 0.95,
				lines: 14,
				face: 0.75, // eyes wear the picked difficulty's mood, sized to the head
				faceGap: 0.03,
			},
			promptRadius: 1.5,
			walkSound: { freq: 440, slideTo: 560, dur: 0.1, gain: 0.06, type: 'sine' },
			enterSound: { freq: 680, slideTo: 760, dur: 0.12, gain: 0.05, type: 'triangle' },
			fullSound: { freq: 880, slideTo: 1320, dur: 0.18, gain: 0.08, type: 'sine' },
			cancelSound: { freq: 330, slideTo: 220, dur: 0.1, gain: 0.07, type: 'triangle' },
		},
		gallery: {
			// Authored props apply on restart; aim/contact tests and settling are live.
			x: 0,
			z: 5.7,
			spacing: 2.0,
			radius: 0.4,
			aimRadius: 2,
			clickPad: 0.02, // right-clicks this far outside a magnet's screen box (in clip space) still pick it
			// The invisible box that hover and right-click read; the magnet floats inside it.
			width: 1.15,
			height: 1.7,
			labelY: 0.1,
			settleTime: 0.35,
			overshoot: 0.12,
			ringY: 0.18,
			ringWidth: 0.06,
			firingMark: { x: 0, z: 4.5 },
			shot: { speed: 20, range: 18, radius: 0.2, damage: 0 },
			shotSound: { freq: 790, slideTo: 350, dur: 0.09, gain: 0.07, type: 'sine' },
			pickSound: { freq: 140, slideTo: 420, dur: 0.2, gain: 0.1, type: 'sine' },
			// Each difficulty is a floating horseshoe magnet; ball count, orbit and face say how hard.
			// Shapes apply on restart; motion, timing and sound are live.
			magnet: {
				hover: 1.2, // arch centre above the floor
				tilt: 0.35, // leans back toward the camera
				lean: 0.45, // each ball's orbit plane tips this far off flat
				arch: 0.38,
				tube: 0.14,
				leg: 0.36,
				tip: 0.16,
				ball: 0.13,
				face: 0.2,
				sag: 0.18, // an unpicked magnet droops this far and dims its pull
				pullRate: 6,
				slamTime: 0.14,
				leapTime: 0.42,
				leapHeight: 0.8,
				stagger: 0.06,
				stickFor: 0.8,
				releaseTime: 0.45,
				punch: 0.22,
				punchTime: 0.35,
				gravity: 16,
				bounce: 0.45,
				fling: 0.6, // share of orbit speed a dropped ball keeps
				roll: 2.2, // floor friction per second
				roam: 0.85, // dropped balls stay this close to their magnet
				rest: 0.55, // where idle balls lie, around the magnet's foot
				moods: {
					easy: { balls: 1, orbit: 0.92, spin: 1.1, bob: 0.07, bobRate: 0.9, buzz: 0, crackle: 0 },
					normal: {
						balls: 2,
						orbit: 0.8,
						spin: 3.2,
						bob: 0.04,
						bobRate: 1.6,
						buzz: 0,
						crackle: 0,
					},
					hard: {
						balls: 3,
						orbit: 0.66,
						spin: 7.5,
						bob: 0.02,
						bobRate: 3,
						buzz: 0.025,
						crackle: 0.35,
					},
				},
				clackSound: { freq: 1900, slideTo: 1300, dur: 0.045, gain: 0.09, type: 'square' },
				thudSound: { freq: 150, slideTo: 80, dur: 0.07, gain: 0.08, type: 'triangle' },
				leapSound: { freq: 300, slideTo: 900, dur: 0.12, gain: 0.05, type: 'sine' },
			},
		},
		// The lobby's camera starts `distance`× back along its view ray; the canvas fades in from `fadeFrom` of the move.
		intro: { distance: 4, fadeFrom: 0.6 },
		// Where you can walk: a rectangle kept over 1 m inside the floor's torn outline
		// (floor.halfX/halfZ minus floor.jag, minus the 1 m). Gallery, seats, dummies and marks all sit inside it.
		bounds: { halfX: 9, halfZ: 6.5 },
		// The props the camera frames; it slides to follow once you leave `followX` or this depth.
		frame: { halfZ: 6.2, followX: 5, followEase: 6 },
		// The lobby's training dummies strafe `dummies.span` either side of these; keep the gallery >2 m off.
		dummyPosts: [
			{ x: -1.5, z: -5.8 },
			{ x: 1.5, z: -5.8 },
		],
		// The lobby floor: finite pale tarmac over a torn rock rim, floating over the desert. Geometry, texture and
		// colours apply on restart. The outline only ever pulls in from the halfX/halfZ rectangle by up to `jag`.
		floor: {
			halfX: 11,
			halfZ: 8.1,
			jag: 0.6,
			seed: 7,
			step: 0.9, // metres between outline vertices
			rockDepth: 3,
			courses: 3,
			courseInset: 0.3, // each rock course juts out this much further than the one above (the camera only sees outward steps), give or take half
			courseJitter: 0.3,
			pixelsPerMeter: 40,
			colors: {
				tarmac: '#f4ecda',
				blotch: '#e4d9c3',
				speck: '#9c8f7a',
				crack: '#a39682',
				chalk: '#ffffff',
				ledge: '#e0c79e',
				rock: '#c4a57c',
				rockDark: '#6a6088',
			},
			speckles: 5200,
			cracks: 13,
			chalkWidth: 0.1,
			seatPad: 0.12,
			circle: { x: 0, z: -3.4, radius: 1.5 },
			hopscotch: { x: -7.4, z: 0.2, cell: 0.95 },
			arcRadius: 9, // gallery arc: a shallow curve 0.9 m behind the cards
		},
		// Schoolyard scenery only; all fence settings apply on restart. Coordinates are fractions
		// of the safe rim rectangle, outside walking bounds even at the smallest supported floor.
		fence: {
			edgeMargin: 0.3,
			height: 1.35,
			bottom: 0.12,
			sag: 0.32,
			bow: 0.12,
			postRadius: 0.12,
			postExtra: 0.22,
			capRadius: 0.16,
			capHeight: 0.1,
			railRadius: 0.025,
			panelWidth: 2.4,
			diamond: 0.65,
			curveSteps: 12,
			radialSegments: 8,
			bollardRadius: 0.23,
			bollardHeight: 0.8,
			bollardCapHeight: 0.14,
			colors: { posts: '#716b80', wire: '#89989a', bollards: '#8caaa3', caps: '#646779' },
			runs: [
				{ from: [-0.9, -1], to: [-0.42, -1] },
				{ from: [0.35, -1], to: [0.88, -1] },
				{ from: [-1, -0.7], to: [-1, -0.18] },
				{ from: [1, 0.05], to: [1, 0.55] },
			],
			bollards: [
				[-0.16, -1],
				[0.1, -1],
				[-1, 0.72],
				[1, -0.72],
			],
		},
		onlineNotice: 'The online lobby is not ready yet. Play local practice.',
		replica: { delay: 0.1, size: 6, depth: 12, precision: 100 },
		respawn: 0.5,
		// Where you spawn and recover: index 0 for team A, 3 for team B. Not drawn.
		marks: [
			{ x: -1.4, z: -1.25 },
			{ x: -1.4, z: 0 },
			{ x: -1.4, z: 1.25 },
			{ x: 1.4, z: -1.25 },
			{ x: 1.4, z: 0 },
			{ x: 1.4, z: 1.25 },
		],
	},
	collision: { epsilon: 1e-6, separation: 1e-3, clampPasses: 8 },
	pips: {
		inset: 0.92,
		size: 12,
		height: 1.1,
		markerMargin: 48,
		markerFont: 14,
		markerBorder: 2,
		markerCorner: 8,
		markerPadding: 4,
	},
	// The hero's movement profile (core/body.js). Obedience first: full speed in ~25 ms, a dead stop, no air.
	tower: {
		x: 18,
		hp: 1400,
		damage: 165,
		rate: 1,
		range: 7.75,
		radius: 1.5,
		speed: 16,
		tell: 0.3,
		ringNear: 3,
	},
	fort: {
		hp: 1400,
		damage: 165,
		rate: 1,
		range: 7.75,
		radius: 1.5,
		speed: 16,
		tell: 0.3,
		ringNear: 3,
	},
	core: {
		x: 40,
		hp: 6000,
		damage: 270,
		rate: 1,
		range: 9,
		radius: 3.5,
		speed: 16,
		tell: 0.3,
		ringNear: 3,
	},
	levels: {
		cap: 10,
		first: 600,
		increment: 100,
		growth: 0.04,
		passive: 8,
		passiveStart: 30,
		takedown: 200,
		victimLevel: 40,
	},
	globes: { heal: 0.15, life: 15, pickup: 1, radius: 0.35, height: 0.6, spin: 2 },
	ball: {
		first: 60,
		interval: 150,
		lateInterval: 30,
		warning: 30,
		life: 45,
		channel: 0.75,
		pickup: 1,
		still: 0.15,
		carrySpeed: 0.85,
		range: 5,
		speed: 14,
		radius: 0.7,
		structureDamage: 0.2,
		damage: 300,
		stun: 0.75,
		silence: 6,
		lock: 1,
		tell: 0.3,
	},
	ballConfetti: {
		count: 96,
		size: 0.16,
		life: 1.4,
		speed: 9,
		speedMin: 0.25,
		lift: 8,
		liftMin: 0.35,
		gravity: 9,
		spin: 8,
	},
	ballView: {
		radius: 0.7,
		height: 0.9,
		carryHeight: 3.4,
		segments: 48,
		ringWidth: 0.35,
		ringBorder: 0.05,
		ringY: 0.09,
		fillY: 0.105,
		channelRadius: 1.3,
		seamWidth: 0.035,
		flightEase: 0.1,
		teamRingRadius: 0.95,
		teamRingWidth: 0.09,
		shadowY: 0.12,
		aimY: 0.135,
		aimFillY: 0.15,
		aimBorder: 0.05,
		gagWidth: 2.4,
		gagHeight: 0.22,
		gagAngle: 0.4,
		throwSquash: -0.22,
		pickupSquash: 0.16,
	},
	base: { x: 44, heal: 0.1 },
	bots: {
		// Logic experiments: bot code may read `tune.bots.exp.<flag>` (truthy or a number) to switch a
		// behaviour variant; `bun run simulate --set bots.exp.<flag>=0,1` sweeps it. Empty on main: land the
		// winner as real code and delete its flag.
		exp: {},
		seed: 2,
		thinkTicks: 6,
		history: 2,
		fileSpacing: 3,
		retreatHp: 0.35,
		meleeRetreatHp: 0.5,
		recoverHp: 0.9,
		retreatDisadvantage: 1,
		supportRange: 12,
		fightRange: 9,
		hold: 0.5,
		sticky: 1,
		laneBehind: 3,
		goalTolerance: 1,
		globeRange: 6,
		burstWindow: 1.5,
		towerExposure: 2,
		stutter: 1,
		chaseHp: 0.25,
		chaseRange: 7,
		dodgeClearance: 0.6,
		zoneClearance: 0.5,
		ballPrepare: 10,
		ballHp: 0.5,
		ballContestHp: 0.5,
		shadowRange: 8,
		escortAhead: 2,
		carrierFlank: 10,
		carrierDanger: 10,
		throwHeroRange: 4,
		throwMargin: 0.5,
		rainHeroes: 2,
		clearMinions: 2,
		siegeFile: 0,
		bruteEscort: 2,
		siegeMinions: 2,
		siegeBackoff: 1,
		siegeLowHp: 0.35,
		openingX: 8,
		easy: {
			focusUntil: 300,
			humanAttackers: 1,
			reaction: 0.45,
			dodgeReaction: 0.3,
			jitter: 0.14,
			leadError: 0.35,
			dodge: 0.2,
			aggression: 0.3,
			catchRate: 0.1,
		},
		normal: {
			reaction: 0.3,
			dodgeReaction: 0.2,
			jitter: 0.08,
			leadError: 0.2,
			dodge: 0.5,
			aggression: 0.6,
			catchRate: 0.3,
		},
		hard: {
			reaction: 0.18,
			dodgeReaction: 0.12,
			jitter: 0.04,
			leadError: 0.1,
			dodge: 0.75,
			aggression: 0.9,
			catchRate: 0.5,
		},
	},
	// Agent protocol settings apply on match start; not debug sliders.
	agents: {
		decision: 0.5,
		maxWait: 30,
		interruptDamage: 0.1,
		nearby: 12,
		observationBytes: 1000,
		precision: 10,
		maxSeconds: 900,
	},
	scripted: { think: 0.1, tell: 0.3, retreat: 0.35, recover: 0.9, file: 2, hold: 3 },
	proof: { batch: 3600, afterKill: 1, siegeLimit: 600, trace: 128, queryBudgetMs: 2 },
	hud: {
		bannerLife: 2.5,
		ending: 1.5,
		recapSources: 3,
		hoverDelay: 0.25, // a world unit's nameplate opens after the cursor rests this long
		longPress: 0.4, // touch hold that opens a HUD card
		inspectHold: 0.35, // pad Y hold that opens a card
		hpTick: 200, // HP per tick on the portrait bar
		warn: 5, // timers pulse in their last seconds
	},
	// Screen-space health bars: CSS pixels except lift (world metres).
	healthBars: {
		heroWidth: 88,
		structureWidth: 104,
		minorWidth: 42,
		height: 10,
		minorHeight: 6,
		border: 2,
		lift: 0.4,
		gap: 5,
		font: 10,
		tickMinGap: 4,
	},
	match: { objective: 180, late: 360, lateGunDamage: 0.05 },
	waves: {
		first: 15,
		interval: 30,
		lateInterval: 15,
		growth: 0.04,
		growthPeriod: 60,
		spawnX: 32,
		structureStandoff: 1,
		fileSpacing: 2,
		rowSpacing: 1.2,
		radius: 0.27,
		aggro: 6,
		leash: 8,
		laneZ: 5.5,
		helpHold: 2,
		soak: 12,
		structureXp: 300,
		abilityStructure: 0.25,
		reinforcement: 'melee', // one more per wave for each enemy tower taken
	},
	minions: {
		brute: {
			count: 1,
			hp: 3500,
			damage: 50,
			structureDamage: 2,
			rate: 0.67,
			range: 1.2,
			speed: 3,
			xp: 120,
			tell: 0.3,
		},
		melee: { count: 3, hp: 400, damage: 18, rate: 0.67, range: 0.9, speed: 3.5, xp: 40, tell: 0.3 },
		ranged: {
			count: 2,
			hp: 280,
			damage: 30,
			rate: 0.67,
			range: 5,
			speed: 3.5,
			xp: 40,
			tell: 0.3,
			shotSpeed: 16,
		},
		wizard: {
			count: 1,
			hp: 220,
			damage: 15,
			rate: 0.67,
			range: 3,
			speed: 3.5,
			xp: 40,
			tell: 0.3,
			shotSpeed: 14,
		},
	},
	laneView: {
		rubbleRadius: 0.7,
		rubbleHeight: 0.35,
		shatterLife: 0.8,
		shatterSpread: 2,
		shatterLift: 1.5,
		shatterPieces: 5,
		shatterSize: 0.5,
		shatterSpin: 3,
		towerHeight: 5,
		fortHeight: 5,
		coreHeight: 8.5,
		domeSegments: 16,
		domeWidth: 0.045,
		crenels: 8,
		coreSpin: 0.4,
		coreWidth: 0.7,
		coreAspect: 1.7,
		shieldLife: 0.3,
		shieldPulse: 0.08,
		coreCrack: 1 / 3,
		corePose: 0.3,
		minionHeight: 1.26,
		bruteRadius: 0.45,
		bruteHeight: 2.1,
		bruteHelmet: 0.8,
		brutePose: 0.6,
		drumHeight: 0.8,
		shaftTop: 0.45,
		shaftBottom: 0.7,
		shaftHeight: 2.4,
		shaftY: 0,
		flagRadius: 0.6,
		flagHeight: 0.8,
		flagY: 1.6,
		flagSides: 4,
		segments: 12,
		capSegments: 4,
		footWidth: 0.5,
		footHeight: 0.12,
		footDepth: 0.4,
		hatRadius: 0.35,
		hatHeight: 0.5,
		stickRadius: 0.05,
		stickHeight: 1.2,
		shieldRadius: 0.32,
		shieldDepth: 0.08,
		aggroLife: 0.5,
		aggroWidth: 6,
		aggroPing: 1.3,
		towerCharge: 0.15,
		fortPose: 0.15,
		meleePose: 0.5,
		rangedPose: 0.4,
		wizardPose: 0.35,
		// Minion swings: the windup peaks at windupHold of the tell and hangs there; the strike overshoots and decays.
		windupHold: 0.65,
		windupSquash: 0.2,
		strikeReach: 0.8,
		strikeDecay: 10,
		strikeFrom: 0.6,
		ringWidth: 0.06,
		ringSegments: 64,
		ringY: 0.09,
		tetherWidth: 0.04,
		tetherHeight: 0.04,
		tetherY: 1.3,
		orbScale: 1.5,
		labelWidth: 3,
		labelHeight: 0.75,
		labelLift: 0.6,
		xpWidth: 256,
		xpHeight: 64,
		xpFont: 28,
		xpBaseline: 0.7,
		xpScale: 2,
		xpY: 2,
		feedbackDecay: 12,
		xpLife: 1,
		xpRise: 1.5,
	},
	hero: {
		hp: 1400,
		level: 1,
		speed: 5, // HotS 4.84; mounted 6.5
		accel: 40,
		friction: 14, // if it feels weightless, lower this first
		stopFriction: 30,
		stopSpeed: 2,
		airAccel: 40, // a flat lane: air behaves like ground
		airSpeedMul: 1,
		radius: 0.45,
		halfHeight: 0.6,
		jumpSpeed: 0,
		gravityMul: 1,
		coyoteTime: 0,
		turnRate: 1080, // degrees per second; facing is cosmetic and nothing waits on it
	},
	heroes: {
		mitts: { hp: 2200, speed: 5.6 },
		carom: { hp: 1300, speed: 5 },
		skip: { hp: 1450, speed: 5 },
	},
	// Silhouettes and costume geometry apply on restart. The collision disc stays 0.45 m.
	silhouettes: {
		segments: 24,
		bodyRadius: 0.29,
		bodyHalfHeight: 0.6,
		discY: 0.08,
		discBorder: 0.06,
		quiverRadius: 0.14,
		quiverHeight: 0.8,
		quiverY: 0.15,
		quiverZ: 0.38,
		arrowCount: 3,
		arrowSpacing: 0.22,
		arrowFan: 0.42,
		arrowTilt: (35 * Math.PI) / 180,
		finCount: 2,
		arrowRadius: 0.045,
		arrowHeight: 1.1,
		arrowY: 0.55,
		fletchingRadius: 0.17,
		fletchingHeight: 0.3,
		mittsWidth: 0.9,
		mittsDepth: 0.8,
		mittsHeight: 0.8,
		corner: 0.16,
		gloveWidth: 0.65,
		gloveDepth: 0.5,
		gloveX: 0.55,
		gloveZ: -0.25,
		fingerRadius: 0.16,
		fingerCount: 4,
		fingerSpacing: 0.14,
		caromRadius: 0.55,
		caromHeight: 1.2,
		racketRadius: 0.32,
		racketTube: 0.055,
		racketX: 0.6,
		racketY: 0.55,
		racketHandle: 0.5,
		racketHandleRadius: 0.05,
		skipWidth: 1.3,
		skipDepth: 0.25,
		skipHeight: 1.5,
		megaphoneRadius: 0.28,
		megaphoneMouth: 0.2,
		megaphoneLength: 0.65,
		megaphoneZ: -0.6,
		megaphoneY: 0.25,
	},
	orders: {
		pick: 0.6, // an order this close to an enemy's silhouette attacks it
		carrot: 0.8, // the pursuit point runs this far ahead along the path
		arrival: 0.05, // done within this radius, with no easing
		stallProgress: 0.3, // repath when progress stays under this fraction of top speed…
		stallTime: 0.25, // …for this long
		grid: 0.5, // A* cell size
		replanDistance: 0.75, // target movement that invalidates an attack path
		rejoinDistance: 0.3, // a duplicate click replans if the hero was displaced this far from its path
		clearance: 0.1, // extra room kept from pillars beyond the body's radius
		attackRange: 5.5, // an attack order walks until the target is this close
	},
	attack: {
		damage: 90,
		rate: 1,
		windup: 0.15,
		backswing: 0.25,
		speed: 24,
		radius: 0.12,
		visualScale: 0.65,
	},
	respawn: { base: 8, perLevel: 2 },
	momentum: { reduction: 2 },
	cast: { cancelLockout: 0.75 },
	catching: { returnTell: 0.5, pocketLife: 6, bagLimit: 6 },
	gloveSlap: { damage: 130, rate: 1, windup: 0.2, backswing: 0.25, range: 3.5, radius: 0.35 },
	toss: { damage: 120, castPoint: 0.35, range: 9, speed: 20, radius: 0.35, cooldown: 5 },
	catch: {
		damageReduction: 0.25, // playtest starting value, not a balance claim
		castPoint: 0,
		duration: 1,
		radius: 2,
		angle: 100,
		speedFactor: 0.5,
		cooldown: 10,
		resetCooldown: 3,
	},
	dive: { castPoint: 0, range: 4, time: 0.25, prone: 0.4, radius: 2, angle: 360, cooldown: 12 },
	mittsView: {
		segments: 48,
		arcInset: 0.94,
		edgeWidth: 0.15,
		timerWidth: 0.08,
		timerGap: 0.025,
		stipplePixels: 3,
		arcLift: 0.005,
		catchY: 0.11,
		catchFillY: 0.125,
		diveY: 0.14,
		pocketY: 0.015,
		pocketRadius: 0.6,
		pocketWidth: 0.055,
		gloveLift: 0.5,
		gloveTurn: 0.5,
		tossPull: 0.65,
		tossLift: 0.32,
		tossLean: 0.22,
		tossTurn: 0.38,
		tossReach: 0.85,
		tossSnap: 0.08,
		tossRecover: 0.2,
		slapReach: 0.5,
		diveLean: 0.7,
		proneTurn: Math.PI / 2,
	},
	abilityView: {
		tellY: 0.087, // above the map's print layers, under the cursor markers
		fillLift: 0.001,
		castLife: 0.15,
		streakLife: 0.25,
		drawLean: 0.14,
		drawTurn: 0.18,
		drawPull: 0.48,
		drawReach: 0.28, // fraction of cast spent reaching into the quiver
		drawSnap: 0.05,
		drawRecover: 0.18,
		drawRecoil: 0.24,
		bowX: -0.38,
		bowY: 0.08,
		bowZ: -0.52,
		bowHeight: 0.95,
		bowCurve: 0.22,
		bowRadius: 0.035,
		bowSegments: 12,
		bowFlex: 0.1,
		handRadius: 0.1,
		handX: 0.24,
		handY: 0.12,
		armRadius: 0.055,
		// E, Rain: `arrows` drop from `height` m, staggered over the delay so all land on the beat.
		// They stick `buried` m deep for `stickLife` s, then sink over `sink` s. On landing the
		// zone flashes for `flashLife` s and an ink ring snaps out `shockGrow` × the radius.
		rain: {
			arrows: 10,
			height: 7,
			stagger: 0.45,
			shaft: 0.8,
			buried: 0.25,
			stickLife: 1.5, // as long as the slow lasts
			sink: 0.25,
			flashLife: 0.12,
			shockLife: 0.3,
			shockGrow: 0.35,
		},
	},
	heroProof: { pixels: 20, canvas: 80, zoom: 4 },

	// Q, Loose: a line skillshot, first hit.
	loose: {
		damage: 230, // about 2.5 autos: worth the aim, the miss risk and Mitts's catch
		castPoint: 0.3,
		range: 11,
		speed: 20, // Ground line plus flight gives an 8 m dodge deadline of about 0.52 s.
		radius: 0.3,
		cooldown: 4,
		height: 1.1, // flight height, for presentation only
		nearMiss: 0.8, // a pass this close to a body's edge cues "close"
	},
	rain: {
		damage: 180,
		castPoint: 0,
		range: 10,
		radius: 2.5,
		delay: 0.7,
		slow: 0.3,
		duration: 1.5,
		cooldown: 6,
	},
	vault: { castPoint: 0, range: 4, time: 0.18, cooldown: 3 },
	// The pad's right stick: hero + dir × range × remap(magnitude).
	stickAim: {
		inMin: 0.25,
		inMax: 0.9,
		outMin: 0.3,
		assistAngle: 10, // degrees: within this of an enemy hero, Q's aim bends toward it…
		assistBend: 0.6, // …by this fraction of the gap
	},
	follow: {
		viewPadding: 1.25,
		minHeight: 1,
		minFov: 0.01,
		fitIterations: 24,
		maxStep: 1 / 60, // camera/FOV spring integration, independent of render frequency
		pan: 20, // metres per second; free camera stays inside the floor
		edgePan: true,
		edgeBand: 32, // CSS pixels; capped to half the viewport on tiny windows
		edgeSpeed: 1, // fraction of pan speed; smoothstep from the band's inner boundary
		height: 20,
		back: 12.5, // pitch = atan(height / back) ≈ 58°
		fov: 40,
		response: 0.12, // seconds for the spring to cover ~90% of a step
		lookAhead: 0.25, // fraction of the way toward the aim point
		lookCap: 3,
	},
	dummies: {
		speed: 3.5,
		flipMin: 0.5, // seconds between strafe reversals, drawn uniformly
		flipMax: 1.4,
		span: 4, // metres either side of the post
		hp: 1400,
		tell: 0.4, // an enemy-visible line before the sparring dummy releases Q
		castEvery: 4, // one sparring dummy casts Loose back while in range
		respawn: 2,
	},
	// The sparring dummies' own body: a burlap sack on a coil spring, all sizes in metres from the disc.
	dummyView: {
		segments: 20,
		springRadius: 0.11,
		springTube: 0.035,
		springTurns: 3,
		springHeight: 0.3,
		sackRadius: 0.38,
		sackHalfHeight: 0.46,
		targetRings: [0.62, 0.42, 0.2], // outer red, cream, bullseye: cap angles in radians
		targetLift: 0.12, // radians the target tilts up from the sack's equator
		seamStitches: 5,
		stitchLength: 0.1,
		stitchWidth: 0.025,
		neckRadius: 0.13,
		neckTube: 0.035,
		headRadius: 0.24,
		eyeX: 0.085,
		eyeY: 0.04,
		eyeSize: 0.11,
		buttonRadius: 0.05,
		mouthY: -0.09,
		mouthWidth: 0.15,
		strawCount: 3,
		strawLength: 0.2,
		strawRadius: 0.035,
		strawFan: 0.5,
		armRadius: 0.085,
		armLength: 0.34,
		armDroop: 0.35, // radians below horizontal at rest
		armY: 0.8, // shoulder height, as a fraction of the sack's height
		wobbleFrequency: 9, // rad/s of the spring wobble
		wobbleDamping: 0.16, // fraction of critical: low rings for longer
		wobbleHit: 4.5, // rad/s a hit throws the top away from the shot
		wobbleRelease: 3.5, // rad/s the lurch that throws a Loose back
		wobbleMax: 0.6, // radians, tilt never exceeds this
		armFlail: 0.5, // arm swing per rad/s of wobble
		hopHeight: 0.12, // metres of each strafing hop at full speed
		hopStride: 1.1, // metres travelled per hop
		hopRock: 0.12, // radians of side-to-side rock per hop
		castLean: 0.35, // radians the dummy rears back during its Loose tell
		castArms: 1.1, // radians the arms rise during the tell
	},
	sounds: {
		slapWindup: { freq: 140, slideTo: 250, type: 'triangle', dur: 0.15, gain: 0.1 },
		slap: { freq: 100, slideTo: 55, type: 'square', dur: 0.1, gain: 0.18 },
		tossWindup: { freq: 230, slideTo: 390, type: 'sine', dur: 0.18, gain: 0.12 },
		toss: { freq: 520, slideTo: 170, type: 'triangle', dur: 0.13, gain: 0.15 },
		tossHit: { freq: 190, slideTo: 60, type: 'sawtooth', dur: 0.12, gain: 0.18 },
		catch: { freq: 430, slideTo: 900, type: 'sine', dur: 0.18, gain: 0.14 },
		dive: { freq: 130, slideTo: 580, type: 'sawtooth', dur: 0.2, gain: 0.13 },
		boardExpired: { freq: 950, slideTo: 420, type: 'triangle', dur: 0.18, gain: 0.08 },
		nock: { freq: 180, slideTo: 480, type: 'triangle', dur: 0.08, gain: 0.12 },
		returnNock: { freq: 300, slideTo: 500, type: 'sine', dur: 0.12, gain: 0.12 },
		returnShot: { freq: 650, slideTo: 220, type: 'triangle', dur: 0.16, gain: 0.14 },
		returnHit: { freq: 350, slideTo: 75, type: 'square', dur: 0.12, gain: 0.2 },
		caught: { freq: 850, slideTo: 240, type: 'sine', dur: 0.16, gain: 0.16 },
		catchExpired: { freq: 280, slideTo: 120, type: 'sine', dur: 0.1, gain: 0.08 },
		channelCancelled: { freq: 210, slideTo: 100, type: 'triangle', dur: 0.12, gain: 0.1 },
		channelEnd: { freq: 520, slideTo: 700, type: 'triangle', dur: 0.12, gain: 0.12 },
		ballContested: { freq: 650, slideTo: 350, type: 'triangle', dur: 0.25, gain: 0.16 },
		ballWarn: { freq: 1800, slideTo: 2100, type: 'sine', dur: 0.5, gain: 0.24 },
		ballSpawn: { freq: 200, slideTo: 1000, type: 'triangle', dur: 0.35, gain: 0.25 },
		ballChannel: { freq: 360, slideTo: 540, type: 'sine', dur: 0.2, gain: 0.1 },
		ballPickup: { freq: 800, slideTo: 1600, type: 'triangle', dur: 0.25, gain: 0.2 },
		ballWindup: { freq: 120, slideTo: 300, type: 'sawtooth', dur: 0.3, gain: 0.13 },
		ballThrow: { freq: 1000, slideTo: 80, type: 'sawtooth', dur: 0.2, gain: 0.22 },
		ballGoal: { freq: 440, slideTo: 1320, type: 'triangle', dur: 0.45, gain: 0.3 },
		ballHit: { freq: 70, slideTo: 600, type: 'square', dur: 0.3, gain: 0.3 },
		ballBounce: { freq: 250, slideTo: 130, type: 'triangle', dur: 0.16, gain: 0.2 },
		ballDrop: { freq: 180, slideTo: 90, type: 'sine', dur: 0.14, gain: 0.12 },
		ballPop: { freq: 1200, slideTo: 40, type: 'square', dur: 0.12, gain: 0.2 },
		ballInterrupted: { freq: 420, slideTo: 180, type: 'square', dur: 0.1, gain: 0.1 },
		ballDenied: { freq: 95, slideTo: 65, type: 'triangle', dur: 0.08, gain: 0.1 },
		core: { freq: 350, slideTo: 70, type: 'sine', dur: 0.25, gain: 0.22 },
		shielded: { freq: 1400, slideTo: 700, type: 'triangle', dur: 0.12, gain: 0.12 },
		levelUp: { freq: 600, slideTo: 1500, type: 'sine', dur: 0.35, gain: 0.2 },
		globe: { freq: 450, slideTo: 950, type: 'sine', dur: 0.22, gain: 0.16 },
		matchOver: { freq: 220, slideTo: 880, type: 'triangle', dur: 0.6, gain: 0.3 },
		tower: { freq: 160, slideTo: 500, type: 'square', dur: 0.18, gain: 0.18 },
		brute: { freq: 120, slideTo: 45, type: 'sawtooth', dur: 0.18, gain: 0.1 },
		melee: { freq: 200, slideTo: 90, type: 'triangle', dur: 0.07, gain: 0.08 },
		ranged: { freq: 510, slideTo: 220, type: 'sine', dur: 0.1, gain: 0.08 },
		wizard: { freq: 880, slideTo: 440, type: 'sine', dur: 0.14, gain: 0.09 },
		xp: { freq: 900, slideTo: 1200, type: 'sine', dur: 0.1, gain: 0.08 },
		structureDown: { freq: 100, slideTo: 30, type: 'sawtooth', dur: 0.4, gain: 0.3 },
		blocked: { freq: 135, slideTo: 55, type: 'square', dur: 0.09, gain: 0.16 },
		attack: { freq: 620, slideTo: 280, type: 'triangle', dur: 0.08, gain: 0.12 },
		attackHit: { freq: 310, slideTo: 120, type: 'triangle', dur: 0.09, gain: 0.18 },
		loose: { freq: 760, slideTo: 190, type: 'sawtooth', dur: 0.14, gain: 0.14 },
		looseHit: { freq: 240, slideTo: 45, type: 'square', dur: 0.18, gain: 0.24 },
		rain: { freq: 90, slideTo: 480, type: 'sine', dur: 0.3, gain: 0.23 },
		vault: { freq: 180, slideTo: 720, type: 'triangle', dur: 0.12, gain: 0.12 },
		// The ref's pea whistle: tweets warble between freq and slideTo; dur is the long final blast.
		whistle: { freq: 2250, slideTo: 2400, type: 'sine', dur: 0.34, gain: 0.07 },
		cardSlap: { freq: 150, slideTo: 55, type: 'square', dur: 0.07, gain: 0.13 },
		squeak: { freq: 1250, slideTo: 2150, type: 'triangle', dur: 0.07, gain: 0.05 },
	},
	// Hero takedowns leave a small crossed-disc print under the victim, with the ref's whistle.
	out: {
		stampY: 0.045, // its own print height, above juice marks (0.03) and below tells
		width: 1.35, // m; square symbol footprint
		slam: 0.12, // s from slamScale down to 1
		slamScale: 1.15,
		squish: 0.03, // slight give as the symbol settles
		tilt: 7, // degrees either way
		opacity: 0.72,
		life: 2, // s until the print has faded away
		hold: 0.2, // fraction of life printed at full strength
		max: 8, // prints kept; the oldest is reused
		streak: 6, // s between takedowns by one team that still count as a streak
		tweet: 0.09, // s per short tweet; one per streak step, up to 3, before the long blast
		warble: 0.03, // s per warble half
		kick: 1.5, // camera kick when your own stamp lands
		splat: { count: 12, speed: 2.4, life: 0.35, size: 0.09 },
	},
	// Every unit death tips over like a cardboard standee (s, except flat, rebound and tint).
	card: {
		fall: 0.24,
		bounce: 0.14,
		press: 0.1,
		hold: 0.7,
		fade: 0.4,
		flat: 0.2,
		rebound: 0.08,
		tint: 0.45,
	},
	// Your sneakers squeak when you reverse at a run; capped so dodging back and forth stays quiet.
	squeak: {
		turn: 125, // degrees of direction change between ticks
		speed: 0.75, // fraction of top speed you must be running at
		window: 0.25, // s a run is remembered through the near stop of a reversal
		cooldown: 0.7, // s between squeaks
		fatigue: 3, // s window; each squeak inside it makes the next one quieter
		quieter: 0.5, // gain multiplier per recent squeak
	},
	juice: {
		slap: { count: 5, speed: 1.2, life: 0.2, size: 0.13 },
		toss: { count: 4, speed: 1.4, life: 0.3, size: 0.08 },
		tossHit: { count: 8, speed: 1.8, life: 0.3, size: 0.09 },
		catch: { count: 6, speed: 0.7, life: 0.35, size: 0.08 },
		dive: { count: 10, speed: 2.4, life: 0.35, size: 0.07, streak: true },
		boardExpired: { count: 6, speed: 0.9, life: 0.5, size: 0.08 },
		caught: { count: 10, speed: 1.8, life: 0.4, size: 0.1 },
		catchExpired: { count: 3, speed: 0.6, life: 0.3, size: 0.06 },
		channelCancelled: { count: 5, speed: 1.1, life: 0.25, size: 0.09 },
		channelEnd: { count: 8, speed: 2, life: 0.35, size: 0.08 },
		ballGoal: {
			freeze: 0.09,
			shake: 0.7,
			kick: 1.5,
			rumbleLow: 0.4,
			rumbleHigh: 0.6,
			rumbleMs: 100,
		},
		ballBurst: { count: 16, speed: 2.5, life: 0.45, size: 0.12 },
		ballDrop: { count: 4, speed: 0.8, life: 0.25, size: 0.08 },
		levelUp: { count: 14, speed: 2, life: 0.5, size: 0.1 },
		globe: { count: 8, speed: 1, life: 0.4, size: 0.08 },
		matchOver: { count: 40, speed: 5, life: 1, size: 0.25 },
		structureShake: 0.6,
		structureKick: 3,
		winKick: 5,
		structureDown: { count: 25, speed: 4, life: 0.8, size: 0.2 },
		blocked: { count: 7, speed: 0.9, life: 0.22, size: 0.08 },
		attackSquash: 0.1,
		castSquash: -0.08,
		vaultSquash: 0.16,
		rainSquash: -0.16,
		flash: 0.07,
		hitstop: 0.065, // your own takedowns only; ignored when shared
		shakeTaken: 0.15,
		shakeRain: 0.12, // your rain landing on someone
		rain: { count: 36, speed: 4.5, life: 0.45, size: 0.12 }, // the landing, not the cast
		shakeTakedown: 0.3,
	},
}

// The body's movement profile is the hero section; its extra keys are ignored by the body.
export const profile = tune.hero
