// Generated by scripts/registry.js (`bun run registry`); do not edit.
import abilities_catch from './abilities/catch/tune.js'
import abilities_dive from './abilities/dive/tune.js'
import abilities_gloveSlap from './abilities/gloveSlap/tune.js'
import abilities_loose from './abilities/loose/tune.js'
import abilities_rain from './abilities/rain/tune.js'
import abilities_toss from './abilities/toss/tune.js'
import abilities_vault from './abilities/vault/tune.js'
import heroes_carom from './heroes/carom/tune.js'
import heroes_mitts from './heroes/mitts/tune.js'
import heroes_skip from './heroes/skip/tune.js'

export const abilities = {
	catch: abilities_catch,
	dive: abilities_dive,
	gloveSlap: abilities_gloveSlap,
	loose: abilities_loose,
	rain: abilities_rain,
	toss: abilities_toss,
	vault: abilities_vault,
}
export const heroes = {
	carom: heroes_carom,
	mitts: heroes_mitts,
	skip: heroes_skip,
}
export const maps = {}
