// --- Tunables ----------------------------------------------------------------
// Moba's live values (docs/moba-plan.md, "Feel numbers"), shared by the debug GUI, the sim and DOM-free tests. Metres and seconds.
export const tune = {
	// Static layout and dressing: applies on mode restart.
	map: {
		halfX: 52,
		halfZ: 13,
		thickness: 1,
		groundGrid: 1,
		baseWallX: 28,
		throat: 8,
		spawnX: 48,
		spawnSpacing: 1.5,
		hedgeInnerX: 12,
		hedgeOuterX: 24,
		hedgeInnerZ: 6,
		hedgeOuterZ: 8,
		hedgeHeight: 1.2,
		scallopRadius: 0.5,
		scallopSpacing: 0.8,
		plazaRadius: 9,
		pillarX: 4.5,
		pillarZ: 4,
		guardX: 13,
		guardZ: 3,
		pillarRadius: 1.1,
		pillarHeight: 2.4,
		pillarSegments: 24,
		capScale: 0.8,
		capHeight: 0.04,
		printLayers: { road: 0.015, dots: 0.03, plaza: 0.045, marks: 0.06, seams: 0.075 },
		lineWidth: 0.06,
		dashLength: 1,
		dashSpacing: 2,
		dotSpacing: 1,
		dotRadius: 0.045,
		printSegments: 32,
		wallHeight: 2.4,
		boundaryThickness: 0.5,
		dummyPosts: [
			{ x: -3, z: -7 },
			{ x: 5, z: -10 },
		],
	},
	collision: { epsilon: 1e-6, separation: 1e-3, clampPasses: 8 },
	pips: { inset: 0.92, size: 12, height: 1.1 },
	// The hero's movement profile (core/body.js). Obedience first: full speed in ~25 ms, a dead stop, no air.
	tower: {
		x: 18,
		hp: 2400,
		damage: 110,
		rate: 1,
		range: 7.75,
		radius: 1.2,
		speed: 16,
		tell: 0.3,
		ringNear: 3,
	},
	fort: {
		x: 29,
		hp: 5000,
		damage: 160,
		rate: 1,
		range: 8.5,
		radius: 2.2,
		speed: 16,
		tell: 0.3,
		ringNear: 3,
	},
	core: {
		x: 40,
		hp: 6000,
		damage: 180,
		rate: 1,
		range: 9,
		radius: 2.5,
		speed: 16,
		tell: 0.3,
		ringNear: 3,
	},
	levels: {
		cap: 10,
		first: 600,
		increment: 100,
		growth: 0.04,
		passive: 8,
		passiveStart: 30,
		takedown: 200,
		victimLevel: 40,
	},
	globes: { heal: 0.15, life: 15, pickup: 1, radius: 0.35, height: 0.6, spin: 2 },
	base: { x: 44, heal: 0.1 },
	scripted: { think: 0.1, tell: 0.3, retreat: 0.35, recover: 0.9, file: 2, hold: 3 },
	proof: { batch: 3600, afterKill: 1, siegeLimit: 600 },
	hud: { bannerLife: 2.5 },
	match: { objective: 180, late: 600, structureTeamSize: 3 }, // temporary pre-Ball HP scaling; applies on restart
	waves: {
		first: 15,
		interval: 30,
		spawnX: 40,
		fileSpacing: 2,
		rowSpacing: 1.2,
		radius: 0.27,
		aggro: 6,
		leash: 8,
		laneZ: 5.5,
		helpHold: 2,
		soak: 12,
		structureXp: 300,
		abilityStructure: 0.25,
	},
	minions: {
		melee: { count: 3, hp: 400, damage: 18, rate: 0.67, range: 0.9, speed: 3.5, xp: 40, tell: 0.3 },
		ranged: {
			count: 2,
			hp: 280,
			damage: 30,
			rate: 0.67,
			range: 5,
			speed: 3.5,
			xp: 40,
			tell: 0.3,
			shotSpeed: 16,
		},
		wizard: {
			count: 1,
			hp: 220,
			damage: 15,
			rate: 0.67,
			range: 3,
			speed: 3.5,
			xp: 40,
			tell: 0.3,
			shotSpeed: 14,
		},
	},
	laneView: {
		rubbleRadius: 0.7,
		rubbleHeight: 0.35,
		towerHeight: 4,
		fortHeight: 5,
		coreHeight: 7,
		domeSegments: 16,
		domeWidth: 0.045,
		crenels: 8,
		crenelSize: 0.5,
		coreSpin: 0.4,
		coreWidth: 0.7,
		coreAspect: 1.7,
		fortDrum: 0.6,
		bannerWidth: 1.4,
		bannerHeight: 1.6,
		bannerPole: 0.06,
		shieldLife: 0.3,
		shieldPulse: 0.08,
		coreCrack: 1 / 3,
		fortPose: 0.2,
		corePose: 0.3,
		minionHeight: 1.26,
		drumHeight: 0.8,
		shaftTop: 0.45,
		shaftBottom: 0.7,
		shaftHeight: 2.4,
		shaftY: 0,
		flagRadius: 0.6,
		flagHeight: 0.8,
		flagY: 1.6,
		flagSides: 4,
		segments: 12,
		capSegments: 4,
		footWidth: 0.5,
		footHeight: 0.12,
		footDepth: 0.4,
		hatRadius: 0.35,
		hatHeight: 0.5,
		stickRadius: 0.05,
		stickHeight: 1.2,
		shieldRadius: 0.32,
		shieldDepth: 0.08,
		tellSize: 1.4,
		tellLift: 0.8,
		tellRangedHeight: 0.45,
		tellLayer: 0.01,
		tellInset: 0.85,
		tellStart: 0.3,
		aggroLife: 0.5,
		aggroWidth: 6,
		aggroPing: 1.3,
		towerCharge: 0.15,
		meleePose: 0.4,
		rangedPose: 0.25,
		wizardPose: 0.15,
		ringWidth: 0.06,
		ringSegments: 64,
		ringY: 0.09,
		tetherWidth: 0.04,
		tetherHeight: 0.04,
		tetherY: 1.3,
		orbScale: 1.5,
		labelWidth: 3,
		labelHeight: 0.75,
		labelLift: 0.6,
		xpWidth: 256,
		xpHeight: 64,
		xpFont: 28,
		xpBaseline: 0.7,
		xpScale: 2,
		xpY: 2,
		feedbackDecay: 12,
		xpLife: 1,
		xpRise: 1.5,
	},
	hero: {
		hp: 1400,
		level: 1,
		speed: 5, // HotS 4.84; mounted 6.5
		accel: 40,
		friction: 14, // if it feels weightless, lower this first
		stopFriction: 30,
		stopSpeed: 2,
		airAccel: 40, // a flat lane: air behaves like ground
		airSpeedMul: 1,
		radius: 0.45,
		halfHeight: 0.6,
		jumpSpeed: 0,
		gravityMul: 1,
		coyoteTime: 0,
		turnRate: 1080, // degrees per second; facing is cosmetic and nothing waits on it
	},
	orders: {
		pick: 0.6, // an order this close to an enemy's silhouette attacks it
		carrot: 0.8, // the pursuit point runs this far ahead along the path
		arrival: 0.05, // done within this radius, with no easing
		stallProgress: 0.3, // repath when progress stays under this fraction of top speed…
		stallTime: 0.25, // …for this long
		grid: 0.5, // A* cell size
		replanDistance: 0.75, // target movement that invalidates an attack path
		rejoinDistance: 0.3, // a duplicate click replans if the hero was displaced this far from its path
		clearance: 0.1, // extra room kept from pillars beyond the body's radius
		attackRange: 5.5, // an attack order walks until the target is this close
	},
	attack: {
		damage: 90,
		rate: 1,
		windup: 0.15,
		backswing: 0.25,
		speed: 24,
		radius: 0.12,
		visualScale: 0.65,
	},
	respawn: { base: 6, perLevel: 2 },
	momentum: { reduction: 2 },
	// Q, Loose: a line skillshot, first hit.
	loose: {
		damage: 140,
		castPoint: 0.133,
		range: 11,
		speed: 24, // tune this before anything else: the dodge window at 8 m is 8 / speed
		radius: 0.3,
		cooldown: 4,
		height: 1.1, // flight height, for presentation only
		nearMiss: 0.8, // a pass this close to a body's edge cues "close"
	},
	rain: {
		damage: 180,
		castPoint: 0,
		range: 10,
		radius: 2.5,
		delay: 0.7,
		slow: 0.3,
		duration: 1.5,
		cooldown: 6,
	},
	vault: { castPoint: 0, range: 4, time: 0.18, cooldown: 3 },
	// The pad's right stick: hero + dir × range × remap(magnitude).
	stickAim: {
		inMin: 0.25,
		inMax: 0.9,
		outMin: 0.3,
		assistAngle: 10, // degrees: within this of an enemy hero, Q's aim bends toward it…
		assistBend: 0.6, // …by this fraction of the gap
	},
	follow: {
		maxStep: 1 / 60, // camera/FOV spring integration, independent of render frequency
		pan: 20, // metres per second; free camera stays inside the floor
		height: 20,
		back: 12.5, // pitch = atan(height / back) ≈ 58°
		fov: 40,
		response: 0.12, // seconds for the spring to cover ~90% of a step
		lookAhead: 0.25, // fraction of the way toward the aim point
		lookCap: 3,
	},
	dummies: {
		speed: 3.5,
		flipMin: 0.5, // seconds between strafe reversals, drawn uniformly
		flipMax: 1.4,
		span: 4, // metres either side of the post
		hp: 1400,
		tell: 0.4, // an enemy-visible line before the sparring dummy releases Q
		castEvery: 4, // one sparring dummy casts Loose back while in range
		respawn: 2,
	},
	sounds: {
		fort: { freq: 125, slideTo: 360, type: 'square', dur: 0.2, gain: 0.2 },
		core: { freq: 350, slideTo: 70, type: 'sine', dur: 0.25, gain: 0.22 },
		shielded: { freq: 1400, slideTo: 700, type: 'triangle', dur: 0.12, gain: 0.12 },
		levelUp: { freq: 600, slideTo: 1500, type: 'sine', dur: 0.35, gain: 0.2 },
		globe: { freq: 450, slideTo: 950, type: 'sine', dur: 0.22, gain: 0.16 },
		matchOver: { freq: 220, slideTo: 880, type: 'triangle', dur: 0.6, gain: 0.3 },
		tower: { freq: 160, slideTo: 500, type: 'square', dur: 0.18, gain: 0.18 },
		melee: { freq: 200, slideTo: 90, type: 'triangle', dur: 0.07, gain: 0.08 },
		ranged: { freq: 510, slideTo: 220, type: 'sine', dur: 0.1, gain: 0.08 },
		wizard: { freq: 880, slideTo: 440, type: 'sine', dur: 0.14, gain: 0.09 },
		xp: { freq: 900, slideTo: 1200, type: 'sine', dur: 0.1, gain: 0.08 },
		structureDown: { freq: 100, slideTo: 30, type: 'sawtooth', dur: 0.4, gain: 0.3 },
		blocked: { freq: 135, slideTo: 55, type: 'square', dur: 0.09, gain: 0.16 },
		attack: { freq: 620, slideTo: 280, type: 'triangle', dur: 0.08, gain: 0.12 },
		attackHit: { freq: 310, slideTo: 120, type: 'triangle', dur: 0.09, gain: 0.18 },
		loose: { freq: 760, slideTo: 190, type: 'sawtooth', dur: 0.14, gain: 0.14 },
		looseHit: { freq: 240, slideTo: 45, type: 'square', dur: 0.18, gain: 0.24 },
		rain: { freq: 90, slideTo: 480, type: 'sine', dur: 0.3, gain: 0.23 },
		vault: { freq: 180, slideTo: 720, type: 'triangle', dur: 0.12, gain: 0.12 },
	},
	juice: {
		levelUp: { count: 14, speed: 2, life: 0.5, size: 0.1 },
		globe: { count: 8, speed: 1, life: 0.4, size: 0.08 },
		matchOver: { count: 40, speed: 5, life: 1, size: 0.25 },
		structureShake: 0.6,
		structureKick: 3,
		winKick: 5,
		structureDown: { count: 25, speed: 4, life: 0.8, size: 0.2 },
		blocked: { count: 7, speed: 0.9, life: 0.22, size: 0.08 },
		attackSquash: 0.1,
		castSquash: -0.08,
		vaultSquash: 0.16,
		rainSquash: -0.16,
		flash: 0.07,
		hitstop: 0.065, // your own takedowns only; ignored when shared
		shakeTaken: 0.15,
		shakeTakedown: 0.3,
	},
}

// The body's movement profile is the hero section; its extra keys are ignored by the body.
export const profile = tune.hero
