// Generated by scripts/registry.js (`bun run registry`); do not edit.
import abilities_bank from './bank/index.js'
import abilities_catch from './catch/index.js'
import abilities_dive from './dive/index.js'
import abilities_gloveSlap from './gloveSlap/index.js'
import abilities_kickOff from './kickOff/index.js'
import abilities_loose from './loose/index.js'
import abilities_rain from './rain/index.js'
import abilities_toss from './toss/index.js'
import abilities_vault from './vault/index.js'

export default {
	bank: abilities_bank,
	catch: abilities_catch,
	dive: abilities_dive,
	gloveSlap: abilities_gloveSlap,
	kickOff: abilities_kickOff,
	loose: abilities_loose,
	rain: abilities_rain,
	toss: abilities_toss,
	vault: abilities_vault,
}
