// Generated by scripts/registry.js (`bun run registry`); do not edit.
import loose from './loose/index.js'
import rain from './rain/index.js'
import vault from './vault/index.js'

export default {
	loose,
	rain,
	vault,
}
