// Writes the moba plugin's registries (docs/mods.md, "Discovery and tune paths"): one plain
// file per kind with static imports sorted by id. A folder is found by convention; this
// script is the only list. `bun run registry` after adding or removing a folder.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const MOBA = fileURLToPath(new URL('../src/plugins/moba/', import.meta.url))

const HEADER = '// Generated by scripts/registry.js (`bun run registry`); do not edit.\n'
const KINDS = ['abilities', 'heroes', 'pieces']

// Import names carry their kind, so an id may be a reserved word (`catch`).
const name = (id) => id.replace(/\W/g, '_')
const key = (id) => (/^[A-Za-z_$][\w$]*$/.test(id) ? id : `'${id}'`)
const entry = (id, value) => (key(id) === value ? value : `${key(id)}: ${value}`)
const folders = (kind) =>
	existsSync(join(MOBA, kind))
		? readdirSync(join(MOBA, kind), { withFileTypes: true })
				.filter((dirent) => dirent.isDirectory())
				.map((dirent) => dirent.name)
				.sort()
		: []
const has = (kind, id, file) => existsSync(join(MOBA, kind, id, file))
const object = (entries) =>
	entries.length ? `{\n${entries.map((line) => `\t${line},\n`).join('')}}` : '{}'

function manifests(kind) {
	const ids = folders(kind).filter((id) => has(kind, id, 'index.js'))
	return (
		HEADER +
		ids.map((id) => `import ${name(`${kind}_${id}`)} from './${id}/index.js'\n`).join('') +
		(ids.length ? '\n' : '') +
		`export default ${object(ids.map((id) => entry(id, name(`${kind}_${id}`))))}\n`
	)
}

// The map table plus maps/recipes.js's lists and lookups, under the exports the game imports.
function maps() {
	const ids = folders('maps').filter((id) => has('maps', id, 'index.js'))
	const imports = [
		...ids.map((id) => `import ${name(`maps_${id}`)} from './${id}/index.js'\n`),
		`import { mapRegistry } from './recipes.js'\n`,
	].sort()
	const entries = ids.map((id) => entry(id, name(`maps_${id}`)))
	return (
		HEADER +
		imports.join('') +
		`\nexport const DEFAULT_MAP = 'overthrow'\n` +
		`export const maps = ${object(entries)}\n` +
		`export const { playableMaps, onlineMaps, mapLayout, matchRecipe } = mapRegistry(maps, DEFAULT_MAP)\n`
	)
}

function tunes() {
	const imports = []
	const groups = ['abilities', 'heroes', 'maps'].map((kind) => {
		const ids = folders(kind).filter((id) => has(kind, id, 'tune.js'))
		for (const id of ids)
			imports.push(`import ${name(`${kind}_${id}`)} from './${kind}/${id}/tune.js'\n`)
		return `export const ${kind} = ${object(ids.map((id) => entry(id, name(`${kind}_${id}`))))}\n`
	})
	return HEADER + imports.join('') + (imports.length ? '\n' : '') + groups.join('')
}

// A kind's view files, namespace-imported per folder: the view registry only views import.
// Heroes key each file by name (`costume.dress`); maps and pieces merge their files' exports
// (`ground`, `scenery`; `view`, `dress`, `onboarding`).
function views(kind, viewFiles, merge = false) {
	const imports = []
	const entries = folders(kind).flatMap((id) => {
		const files = viewFiles.filter((file) => has(kind, id, `${file}.js`))
		for (const file of files)
			imports.push(`import * as ${name(`${id}_${file}`)} from './${id}/${file}.js'\n`)
		return files.length
			? [
					entry(
						id,
						`{ ${files.map((file) => `${merge ? '...' : `${file}: `}${name(`${id}_${file}`)}`).join(', ')} }`,
					),
				]
			: []
	})
	return (
		HEADER + imports.join('') + (imports.length ? '\n' : '') + `export default ${object(entries)}\n`
	)
}

// Path (relative to the moba plugin) → the file's expected contents.
export function registryFiles() {
	return {
		...Object.fromEntries(KINDS.map((kind) => [`${kind}/index.js`, manifests(kind)])),
		'maps/index.js': maps(),
		'tunes.js': tunes(),
		'heroes/views.js': views('heroes', ['costume', 'numbers']),
		'maps/views.js': views('maps', ['ground', 'scenery'], true),
		'pieces/views.js': views('pieces', ['view'], true),
	}
}

if (import.meta.main)
	for (const [path, contents] of Object.entries(registryFiles())) {
		const file = join(MOBA, path)
		if (existsSync(file) && readFileSync(file, 'utf8') === contents) continue
		mkdirSync(dirname(file), { recursive: true })
		writeFileSync(file, contents)
		console.log(`wrote src/plugins/moba/${path}`)
	}
