// Generated by scripts/registry.js (`bun run registry`); do not edit.
import pieces_ball from './ball/index.js'
import pieces_bots from './bots/index.js'
import pieces_camps from './camps/index.js'
import pieces_dummies from './dummies/index.js'
import pieces_flag from './flag/index.js'
import pieces_minions from './minions/index.js'
import pieces_structures from './structures/index.js'

export default {
	ball: pieces_ball,
	bots: pieces_bots,
	camps: pieces_camps,
	dummies: pieces_dummies,
	flag: pieces_flag,
	minions: pieces_minions,
	structures: pieces_structures,
}
