// Generated by scripts/registry.js (`bun run registry`); do not edit.
import * as ball_view from './ball/view.js'
import * as dummies_view from './dummies/view.js'
import * as flag_view from './flag/view.js'
import * as structures_view from './structures/view.js'

export default {
	ball: { ...ball_view },
	dummies: { ...dummies_view },
	flag: { ...flag_view },
	structures: { ...structures_view },
}
